# Generated by Django 5.2.4 on 2025-07-25 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="コンタクトID"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="氏名")),
                (
                    "email",
                    models.EmailField(max_length=254, verbose_name="メールアドレス"),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="種類"
                    ),
                ),
                ("message", models.TextField(verbose_name="メッセージ")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="問い合わせ時間"
                    ),
                ),
            ],
            options={
                "verbose_name": "お問い合わせ",
                "verbose_name_plural": "お問い合わせ",
                "db_table": "contacts",
            },
        ),
    ]
