# Generated by Django 5.2.4 on 2025-07-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_contact_options_alter_contact_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contact",
            name="category",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name="contact",
            name="message",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="contact",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterModelTable(
            name="contact",
            table="contacts",
        ),
    ]
