# Generated by Django 5.2.4 on 2025-07-25 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("lectures", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID（主キー）"
                    ),
                ),
                (
                    "attendance_year",
                    models.IntegerField(blank=True, null=True, verbose_name="受講年度"),
                ),
                (
                    "attendance_confirm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="出欠の有無"
                    ),
                ),
                (
                    "weekly_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="毎回のレポート・テスト",
                    ),
                ),
                (
                    "midterm_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="中間のレポート・テスト",
                    ),
                ),
                (
                    "final_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="期末のレポート・テスト",
                    ),
                ),
                (
                    "past_exam_possession",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="過去問の所持",
                    ),
                ),
                (
                    "grades",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="成績"
                    ),
                ),
                (
                    "credit_level",
                    models.IntegerField(blank=True, null=True, verbose_name="単位取得"),
                ),
                (
                    "interest_level",
                    models.IntegerField(blank=True, null=True, verbose_name="面白さ"),
                ),
                (
                    "skill_level",
                    models.IntegerField(blank=True, null=True, verbose_name="スキル"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="コメント"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="lectures.lecture",
                        verbose_name="講義ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "レビュー",
                "verbose_name_plural": "レビュー",
                "db_table": "reviews",
            },
        ),
        migrations.CreateModel(
            name="ReviewLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ID（主キー）"
                    ),
                ),
                (
                    "attendance_year",
                    models.IntegerField(blank=True, null=True, verbose_name="受講年度"),
                ),
                (
                    "attendance_confirm",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="出欠の有無"
                    ),
                ),
                (
                    "weekly_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="毎回のレポート・テスト",
                    ),
                ),
                (
                    "midterm_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="中間のレポート・テスト",
                    ),
                ),
                (
                    "final_assignments",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="期末のレポート・テスト",
                    ),
                ),
                (
                    "past_exam_possession",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="過去問の所持",
                    ),
                ),
                (
                    "grades",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="成績"
                    ),
                ),
                (
                    "credit_level",
                    models.IntegerField(blank=True, null=True, verbose_name="単位取得"),
                ),
                (
                    "interest_level",
                    models.IntegerField(blank=True, null=True, verbose_name="面白さ"),
                ),
                (
                    "skill_level",
                    models.IntegerField(blank=True, null=True, verbose_name="スキル"),
                ),
                (
                    "comments",
                    models.TextField(blank=True, null=True, verbose_name="コメント"),
                ),
                (
                    "status",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="状況"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="投稿時間"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lecture",
                        verbose_name="講義ID",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
            ],
            options={
                "verbose_name": "レビューログ",
                "verbose_name_plural": "レビューログ",
                "db_table": "review_logs",
            },
        ),
        migrations.CreateModel(
            name="Like",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="いいね時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.review",
                        verbose_name="レビューID",
                    ),
                ),
            ],
            options={
                "verbose_name": "いいね",
                "verbose_name_plural": "いいね",
                "db_table": "likes",
                "unique_together": {("review", "user")},
            },
        ),
        migrations.CreateModel(
            name="DeleteReviewRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="報告時間"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ユーザーID",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reviews.review",
                        verbose_name="レビューID",
                    ),
                ),
            ],
            options={
                "verbose_name": "レビュー削除リクエスト",
                "verbose_name_plural": "レビュー削除リクエスト",
                "db_table": "delete_review_requests",
                "unique_together": {("review", "user")},
            },
        ),
    ]
