# Generated by Django 5.2.4 on 2025-07-26 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_remove_lecturelabel_label_and_more"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name="DeleteReviewRequest",
        ),
        migrations.DeleteModel(
            name="Like",
        ),
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.AlterModelOptions(
            name="reviewlog",
            options={},
        ),
        migrations.AlterField(
            model_name="review",
            name="attendance_confirm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="attendance_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="credit_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="final_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="grades",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="review",
            name="interest_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="lectures.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="midterm_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="past_exam_possession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="skill_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="weekly_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="attendance_confirm",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="attendance_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="comments",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="credit_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="final_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="grades",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="interest_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="lectures.lecture"
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="midterm_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="past_exam_possession",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="skill_level",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="weekly_assignments",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
