# Generated by Django 5.2.4 on 2025-07-30 12:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_like_unique_together_remove_like_review_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="attendance_confirm",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="review",
            name="comments",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="review",
            name="final_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="review",
            name="grades",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="review",
            name="midterm_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="review",
            name="past_exam_possession",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="weekly_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="attendance_confirm",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="comments",
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="final_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="grades",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="midterm_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="past_exam_possession",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="weekly_assignments",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
