# Generated by Django 5.2.4 on 2025-07-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_review_attendance_confirm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="final_assignments",
        ),
        migrations.RemoveField(
            model_name="review",
            name="midterm_assignments",
        ),
        migrations.RemoveField(
            model_name="review",
            name="past_exam_possession",
        ),
        migrations.RemoveField(
            model_name="review",
            name="weekly_assignments",
        ),
        migrations.RemoveField(
            model_name="reviewlog",
            name="final_assignments",
        ),
        migrations.RemoveField(
            model_name="reviewlog",
            name="midterm_assignments",
        ),
        migrations.RemoveField(
            model_name="reviewlog",
            name="past_exam_possession",
        ),
        migrations.RemoveField(
            model_name="reviewlog",
            name="weekly_assignments",
        ),
        migrations.AddField(
            model_name="review",
            name="final_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="final_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="midterm_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="midterm_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="past_report_possession",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="past_test_possession",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="weekly_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="review",
            name="weekly_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="final_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="final_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="midterm_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="midterm_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="past_report_possession",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="past_test_possession",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="weekly_reports",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="weekly_tests",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
