# Generated by Django 5.2.4 on 2025-07-31 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_review_credit_level_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="attendance_confirm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "no"),
                    ("sometimes", "sometimes"),
                    ("always", "always"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="attendance_confirm",
            field=models.CharField(
                blank=True,
                choices=[
                    ("no", "no"),
                    ("sometimes", "sometimes"),
                    ("always", "always"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                ],
                max_length=20,
            ),
        ),
    ]
