# Generated by Django 5.2.4 on 2025-07-31 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reviews",
            "0006_alter_review_attendance_confirm_alter_review_grades_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                    ("undecided", "undecided"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                    ("undecided", "undecided"),
                ],
                max_length=20,
            ),
        ),
    ]
