# Generated by Django 5.2.4 on 2025-07-31 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_alter_review_grades_alter_reviewlog_grades"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("very_good", "very_good"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                    ("undecided", "undecided"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewlog",
            name="grades",
            field=models.CharField(
                blank=True,
                choices=[
                    ("excellent", "excellent"),
                    ("very_good", "very_good"),
                    ("good", "good"),
                    ("pass", "pass"),
                    ("fail", "fail"),
                    ("undecided", "undecided"),
                ],
                max_length=20,
            ),
        ),
    ]
