# Generated by Django 5.2.4 on 2025-08-01 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_alter_review_grades_alter_reviewlog_grades"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewlog",
            name="status",
        ),
        migrations.AddField(
            model_name="reviewlog",
            name="action",
            field=models.CharField(
                blank=True,
                choices=[
                    ("create", "create"),
                    ("update", "update"),
                    ("delete", "delete"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
