version: '3.8'

services:
  devcontainer:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://kaede:kaede@db:5432/kaede
    volumes:
      - ..:/workspace
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: tail -f /dev/null

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://kaede:kaede@db:5432/kaede
    volumes:
      - ..:/workspace
      - ../backend:/app
      - backend_cache:/app/.cache
    depends_on:
      - db
    stdin_open: true
    tty: true
    command: >
      sh -c "python manage.py migrate && 
             python manage.py runserver 0.0.0.0:8000"

  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ../frontend:/app
      - frontend_node_modules:/app/node_modules
      - frontend_cache:/app/.next
    stdin_open: true
    tty: true
    command: npm run dev

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=kaede
      - POSTGRES_USER=kaede
      - POSTGRES_PASSWORD=kaede
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  backend_cache:
  frontend_node_modules:
  frontend_cache: