# Generated by Django 5.2.4 on 2025-07-25 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="ラベルID"
                    ),
                ),
                (
                    "label_name",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="ラベル名"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "ラベル",
                "verbose_name_plural": "ラベル",
                "db_table": "labels",
            },
        ),
        migrations.CreateModel(
            name="Lecture",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="講義ID"
                    ),
                ),
                (
                    "lecture_name",
                    models.CharField(max_length=200, verbose_name="授業名"),
                ),
                (
                    "teacher_name",
                    models.CharField(max_length=100, verbose_name="主担当教員名"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
            ],
            options={
                "verbose_name": "講義",
                "verbose_name_plural": "講義",
                "db_table": "lectures",
            },
        ),
        migrations.CreateModel(
            name="LectureDetail",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="講義詳細ID"
                    ),
                ),
                (
                    "lecture_code",
                    models.CharField(max_length=50, verbose_name="講義コード"),
                ),
                (
                    "syllabus_url",
                    models.URLField(blank=True, null=True, verbose_name="シラバスURL"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="開講場所"
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="開講部局"
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="科目区分"
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="履修年次"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="lectures.lecture",
                        verbose_name="講義ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "講義詳細",
                "verbose_name_plural": "講義詳細",
                "db_table": "lecture_details",
            },
        ),
        migrations.CreateModel(
            name="LectureDetailTime",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True, serialize=False, verbose_name="時間割ID"
                    ),
                ),
                ("year", models.IntegerField(verbose_name="年度")),
                ("term", models.CharField(max_length=20, verbose_name="ターム")),
                ("day_of_week", models.CharField(max_length=10, verbose_name="曜日")),
                ("time_period", models.CharField(max_length=20, verbose_name="時限")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="作成時間"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新時間"),
                ),
                (
                    "lecture_detail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="times",
                        to="lectures.lecturedetail",
                        verbose_name="講義詳細ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "講義時間割",
                "verbose_name_plural": "講義時間割",
                "db_table": "lecture_detail_times",
            },
        ),
        migrations.CreateModel(
            name="LectureLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.label",
                        verbose_name="ラベルID",
                    ),
                ),
                (
                    "lecture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="lectures.lecture",
                        verbose_name="講義ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "講義ラベル関連",
                "verbose_name_plural": "講義ラベル関連",
                "db_table": "lecture_labels",
                "unique_together": {("lecture", "label")},
            },
        ),
    ]
