# Generated by Django 5.2.4 on 2025-07-26 06:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LectureLabel",
        ),
        migrations.DeleteModel(
            name="Label",
        ),
        migrations.AlterModelOptions(
            name="lecture",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturedetail",
            options={},
        ),
        migrations.AlterModelOptions(
            name="lecturedetailtime",
            options={},
        ),
        migrations.AlterField(
            model_name="lecture",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="lecture_name",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="teacher_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecture",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="faculty",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="grade",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="lecture",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="lectures.lecture",
            ),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="lecture_code",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="location",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="syllabus_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="day_of_week",
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="lecture_detail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="times",
                to="lectures.lecturedetail",
            ),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="term",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="time_period",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="year",
            field=models.IntegerField(),
        ),
    ]
