# Generated by Django 5.2.4 on 2025-07-30 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0002_remove_lecturelabel_label_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lecture_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="faculty",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="grade",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="lecture_code",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="location",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="lecturedetail",
            name="syllabus_url",
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name="lecturedetailtime",
            name="day_of_week",
            field=models.CharField(max_length=20),
        ),
    ]
