# Generated by Django 5.2.4 on 2025-07-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lectures", "0003_alter_lecture_lecture_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lecture",
            name="lecture_name",
            field=models.CharField(max_length=300),
        ),
    ]
