# Generated by Django 5.2.4 on 2025-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_user_admission_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="admission_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="faculty",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="university_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="action",
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="category",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="department",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="email",
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="faculty",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="university_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="userlog",
            name="username",
            field=models.CharField(max_length=50),
        ),
    ]
