# Generated by Django 5.2.4 on 2025-08-01 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_admission_year_alter_user_category_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userlog",
            name="action",
            field=models.CharField(
                choices=[
                    ("create", "create"),
                    ("update", "update"),
                    ("delete", "delete"),
                ],
                max_length=20,
            ),
        ),
    ]
